apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backstage
  - ../../base/aiops

patches:
  - target:
      kind: Ingress
      name: backstage
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: backstage.ipp.local
  - target:
      kind: Ingress
      name: aiops-engine
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: aiops.ipp.local

images:
  - name: ipp-platform/backstage
    newTag: latest
  - name: ipp-platform/aiops-engine
    newTag: latest
